<?php

/**
 * Implementation of hook_block()
 */
function dcse_biljett_count_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Biljett.com current ticket count'), 
      'weight' => 0, 
      'status' => 0, 
      'region' => '',
      'cache' => BLOCK_CACHE_GLOBAL
    );

    return $blocks;
  }
  else if ($op == 'view') {
    switch ($delta) {
      case 0:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => '', 
          'content' => _dcse_biljett_count_block_view(),
        );
        break;
    }
    return $block;
  }
}

/**
 * Render the block
 * TODO: Lots of hard-coded stuff here, should be generalized
 */
function _dcse_biljett_count_block_view() {
  // The cache only clears on cron run, which doesn't happen that frequently, so cache_get() may return entries that
  // have expired. Why we need to check expire time manually to prevent using stale data.
  if (($cache = cache_get('dcse_biljett_count:count')) && !empty($cache->data) && (time() < $cache->expire)) {
    return $cache->data;
  }
  
  else {
    $qp = htmlqp('http://www.biljett.com/drupalcampstockholm2011');
    
    // Grabs the number of tickets available
    preg_match('/\d+/i', $qp->find('label[for="quantity_164"]:eq(6)')->text(), $result);
    
    // We cache the result for ten minutes, before it expires, to avoid unnecessary requests to biljett.com
    cache_set('dcse_biljett_count:count', $result[0], 'cache', strtotime('+10 minutes'));
    return $result[0];
  }
}